modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
#issueTrackerURL = "https://github.com/henkelmax/easy-villagers/issues"
[[mods]]
modId = "plant_farms"
#version = "${mod_version}"
displayName = "Plant Farms"
#updateJSONURL = "https://update.maxhenkel.de/neoforge/plant_farms"
#displayURL = "https://www.curseforge.com/minecraft/mc-mods/easy-villagers"
logoFile = "../assets/plant_farms/textures/gui/icons/icon.png"
authors = "awesomeshot5051"
description = '''Plant Farms'''
[[dependencies.plant_farms]]
modId = "neoforge"
type = "required"
version = "21.3.11-beta"
ordering = "NONE"
side = "BOTH"
[[dependencies.plant_farms]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.3]"
ordering = "NONE"
side = "BOTH"
[[dependencies.plant_farms]]
modId = "jei"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.plant_farms]]
modId = "theoneprobe"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.plant_farms]]
modId = "jade"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"