{
  "formatVersion": "1.1",
  "component": {
    "group": "com.awesomeshot5051",
    "module": "plant_farms",
    "version": "1.21.3-1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plant_farms-1.21.3-1.1.0.jar",
          "url": "plant_farms-1.21.3-1.1.0.jar",
          "size": 1002518,
          "sha512": "76be69aa94eab79fddfa2d8ced008d7b40c15be2e83dc65d2f5b519eb4d8f42cb043725bce13b9b20a4cf7baa205c2b840cf6f731013b1aa3ee544c011b92ccd",
          "sha256": "45d160008ff704f060c3901c65760d04ccb3c6a22bbfb55d8bcb6671c6ec2ddb",
          "sha1": "a1f30afa53d94d513baa595d463073bd8f7fe225",
          "md5": "8feef05a921494fd090dd49adf8b3ab2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5846076"
          }
        },
        {
          "group": "de.maxhenkel.corelib",
          "module": "corelib",
          "version": {
            "requires": "1.21.3-2.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "plant_farms-1.21.3-1.1.0.jar",
          "url": "plant_farms-1.21.3-1.1.0.jar",
          "size": 1002518,
          "sha512": "76be69aa94eab79fddfa2d8ced008d7b40c15be2e83dc65d2f5b519eb4d8f42cb043725bce13b9b20a4cf7baa205c2b840cf6f731013b1aa3ee544c011b92ccd",
          "sha256": "45d160008ff704f060c3901c65760d04ccb3c6a22bbfb55d8bcb6671c6ec2ddb",
          "sha1": "a1f30afa53d94d513baa595d463073bd8f7fe225",
          "md5": "8feef05a921494fd090dd49adf8b3ab2"
        }
      ]
    }
  ]
}
