[oak_farm]
	#The time in ticks the spruce farm takes to spawn a oak
	#Range: 60 ~ 60
	spawn_time = 60

[villager]
	#If the villager reputation should be the same for every player
	#This affects the prices of cured/converted villagers and the prices of the auto trader
	universal_reputation = true

[spruce_farm]
	#The time in ticks the spruce farm takes to spawn a spruce
	#Range: 60 ~ 60
	spawn_time = 60

[birch_farm]
	#The time in ticks the birch farm takes to spawn a birch
	#Range: 60 ~ 60
	spawn_time = 60

[jungle_farm]
	#The time in ticks the elder azalea farm takes to spawn an elder azalea
	#Range: 60 ~ 60
	spawn_time = 60

[dark_oak_farm]
	#The time in ticks the darkOak farm takes to spawn an darkOak
	#Range: 60 ~ 60
	spawn_time = 60

[acacia_farm]
	#The time in ticks the acacia farm takes to spawn a acacia
	#Range: 60 ~ 60
	spawn_time = 60

[azalea_farm]
	#The time in ticks the azalea farm takes to spawn a azalea
	#Range: 60 ~ 60
	spawn_time = 60

[mangrove_farm]
	#The time in ticks the mangrove farm takes to spawn a mangrove
	#Range: 60 ~ 60
	spawn_time = 60

[cherry_farm]
	#The time in ticks the cherry farm takes to spawn an cherry
	#Range: 60 ~ 60
	spawn_time = 60

[chorus_farm]
	#The time in ticks the chorus plant takes to drop stuff
	#Range: 60 ~ 60
	spawn_time = 60

[crimson_farm]
	#The time in ticks the crimson farm takes to drop stuff
	#Range: 60 ~ 60
	spawn_time = 60

[warped_farm]
	#The time in ticks the warped farm takes to drop stuff
	#Range: 60 ~ 60
	spawn_time = 60

[wart_farm]
	#The time in ticks the nether wart farm takes to drop stuff
	#Range: 60 ~ 60
	spawn_time = 60

[wheat_farm]
	#The time in ticks the wheat farm takes to spawn wheat
	#Range: 60 ~ 60
	spawn_time = 60

[carrot_farm]
	#The time in ticks the carrot farm takes to spawn carrots
	#Range: 60 ~ 60
	spawn_time = 60

[potato_farm]
	#The time in ticks the potato farm takes to spawn potatoes
	#Range: 60 ~ 60
	spawn_time = 60

[beetroot_farm]
	#The time in ticks the beetroot farm takes to spawn beetroots
	#Range: 60 ~ 60
	spawn_time = 60

[pumpkin_farm]
	#The time in ticks the pumpkin farm takes to spawn pumpkins
	#Range: 60 ~ 60
	spawn_time = 60

[melon_farm]
	#The time in ticks the melon farm takes to spawn melons
	#Range: 60 ~ 60
	spawn_time = 60

[sugar_cane_farm]
	#The time in ticks the sugar cane farm takes to spawn sugar canes
	#Range: 60 ~ 60
	spawn_time = 60

[cocoa_bean_farm]
	#The time in ticks the cocoa bean farm takes to spawn cocoa beans
	#Range: 60 ~ 60
	spawn_time = 60

[sweet_berry_farm]
	#The time in ticks the sweet berry farm takes to spawn sweet berries
	#Range: 60 ~ 60
	spawn_time = 60

[bamboo_farm]
	#The time in ticks the bamboo farm takes to spawn bamboo
	#Range: 60 ~ 60
	spawn_time = 60

[dandelion_farm]
	#The time in ticks the dandelion farm takes to spawn dandelions
	#Range: 60 ~ 60
	spawn_time = 60

[poppy_farm]
	#The time in ticks the poppy farm takes to spawn poppies
	#Range: 60 ~ 60
	spawn_time = 60

[orchid_farm]
	#The time in ticks the blue orchid farm takes to spawn blue orchids
	#Range: 60 ~ 60
	spawn_time = 60

[allium_farm]
	#The time in ticks the allium farm takes to spawn alliums
	#Range: 60 ~ 60
	spawn_time = 60

[azure_farm]
	#The time in ticks the azure bluet farm takes to spawn azure bluets
	#Range: 60 ~ 60
	spawn_time = 60

[red_farm]
	#The time in ticks the red tulip farm takes to spawn red tulips
	#Range: 60 ~ 60
	spawn_time = 60

[orange_farm]
	#The time in ticks the orange tulip farm takes to spawn orange tulips
	#Range: 60 ~ 60
	spawn_time = 60

[white_farm]
	#The time in ticks the white tulip farm takes to spawn white tulips
	#Range: 60 ~ 60
	spawn_time = 60

[pink_farm]
	#The time in ticks the pink tulip farm takes to spawn pink tulips
	#Range: 60 ~ 60
	spawn_time = 60

[daisy_farm]
	#The time in ticks the oxeye daisy farm takes to spawn oxeye daisies
	#Range: 60 ~ 60
	spawn_time = 60

[cornflower_farm]
	#The time in ticks the cornflower farm takes to spawn cornflowers
	#Range: 60 ~ 60
	spawn_time = 60

[lilly_farm]
	#The time in ticks the lily of the valley farm takes to spawn lilies
	#Range: 60 ~ 60
	spawn_time = 60

[sunflower_farm]
	#The time in ticks the sunflower farm takes to spawn sunflowers
	#Range: 60 ~ 60
	spawn_time = 60

[lilac_farm]
	#The time in ticks the lilac farm takes to spawn lilacs
	#Range: 60 ~ 60
	spawn_time = 60

[rose_farm]
	#The time in ticks the rose bush farm takes to spawn rose bushes
	#Range: 60 ~ 60
	spawn_time = 60

[peony_farm]
	#The time in ticks the peony farm takes to spawn peonies
	#Range: 60 ~ 60
	spawn_time = 60

[gcarrot_farm]
	#The time in ticks the golden carrot farm takes to spawn golden carrots
	#Range: 60 ~ 60
	spawn_time = 60

[vine_farm]
	#The time in ticks the vine farm takes to spawn vines
	#Range: 60 ~ 60
	spawn_time = 60

[mushroom_farm]
	#The time in ticks the mushroom farm takes to spawn mushrooms
	#Range: 60 ~ 60
	spawn_time = 60

[kelp_farm]
	#The time in ticks the Kelp farm takes to spawn Kelp
	#Range: 60 ~ 60
	spawn_time = 60

[leaf_farm]
	#The time in ticks the Drip Leaf farm takes to spawn Drip Leaves
	#Range: 60 ~ 60
	spawn_time = 60

[seagrass_farm]
	#The time in ticks the seagrass farm takes to spawn seagrass
	#Range: 60 ~ 60
	spawn_time = 60

[pad_farm]
	#The time in ticks the lily pad farm takes to spawn lily pads
	#Range: 60 ~ 60
	spawn_time = 60
